services:
  - name: fastapi-backend
    type: worker  # Change from 'web' to 'worker' (free tier available!)
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PORT
        value: 8000

  - name: react-frontend
    type: web
    env: static
    buildCommand: |
      npm install
      npm run build
    staticPublishPath: ./build
    plan: free
